version: "3.7"

networks:
  devcrown:
    driver: bridge

services:
  app:
    build:
      args:
        user: developer
        uid: 6543
      context: ./
      dockerfile: Dockerfile
    image: php-composer
    container_name: php-composer-container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # - ./src:/var/www
      - ./docker/php-config/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
      - ./src:/var/www/html:delegated
    environment:
      APP_NAME: ${APP_NAME}
      APP_URL: ${APP_URL}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      LOG_CHANNEL: ${LOG_CHANNEL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    networks:
      - devcrown

  db:
    image: mysql:5.7
    container_name: mysql-5-7-container
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql:delegated
    networks:
      - devcrown

  nginx:
      image: nginx:stable-alpine
      container_name: nginx-container
      ports:
        - "8000:80"
      volumes:
        - ./src:/var/www/html:cached
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      networks:
        - devcrown